core-jr/Models/Entities/BusinessData.cs
using System.ComponentModel.DataAnnotations;

namespace core_jr.Models
{
	public class BusinessData
	{
		[Key]
		public int BusinessDataId { get; set; }		
		public string CompanyName { get; set; }
		public string CompanyLogoPath { get; set; }
		public string CompanyLogo { get; set; }
		public string CompanyAddress { get; set; }
		public string Website { get; set; }
		public string Email { get; set; }
		public int CompanyPhone { get; set; }
		public string ReturnPolicy { get; set; }
	}

	public class BusinessDataDto
	{		
		public int BusinessDataId { get; set; }		
		public string CompanyName { get; set; }
		public IFormFile CompanyLogoFile { get; set; }
		public string CompanyAddress { get; set; }
		public string Website { get; set; }
		public string Email { get; set; }
		public int CompanyPhone { get; set; }
		public string ReturnPolicy { get; set; }
		public string CompanyLogo { get; set; }
	}	
}

core-jr/Controllers/Config/ConfigController.cs
using core_jr.Controllers.Patients;
using core_jr.Data;
using core_jr.Helpers;
using core_jr.Models;
using core_jr.Providers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace core_jr.Controllers.Config
{
    public class ConfigController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ILogger<ConfigController> _logger;
		private readonly UploadfilesHelper _helperUpload;
		private readonly PathProvider _pathProvider;
		public ConfigController(AppDbContext context, IWebHostEnvironment env, ILogger<ConfigController> logger, UploadfilesHelper helperUpload, PathProvider pathProvider)
        {
            _context = context;
            _logger = logger;
			_helperUpload = helperUpload;
			_pathProvider = pathProvider;
		}
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ThemeStyle()
        {
			return PartialView("~/Views/Config/ThemeStyle/ThemeStyle.cshtml");
		}

        [HttpGet]
        public IActionResult BusinessData(int BusinessDataId=0)             
        {
            BusinessData businessData = _context.BusinessData.FirstOrDefault();
            BusinessData businessModel = new();
            if (businessData!=null)
            {
                businessModel = businessData;
            }
			return PartialView("~/Views/Config/BusinessData/BusinessData.cshtml",businessModel);
		}
        [HttpPost]
        public async Task<IActionResult> SaveBusinessData(BusinessDataDto dataBDIn)
        {
            try
            {
				string routeImg = null;
				string filePath = "";
				string ImageName = "";
				string directory = "Img/CompanyLogo/";
				
				if (dataBDIn.BusinessDataId==0)
                {
                    BusinessData businessDataCreate = new();
					if (dataBDIn.CompanyLogoFile != null)
					{
						ImageName =Guid.NewGuid().ToString()+ dataBDIn.CompanyLogoFile.FileName;
						filePath = await _helperUpload.UploadFilesAsync(dataBDIn.CompanyLogoFile, ImageName, Folders.CompanyLogo);
						if (filePath != null)
						{
							routeImg = directory + ImageName;
						}
					}
					businessDataCreate.CompanyName = dataBDIn.CompanyName;
					businessDataCreate.CompanyLogoPath = routeImg;
					businessDataCreate.CompanyAddress = dataBDIn.CompanyAddress;
					businessDataCreate.Website = dataBDIn.Website;
					businessDataCreate.Email = dataBDIn.Email;
					businessDataCreate.CompanyPhone = dataBDIn.CompanyPhone;
					businessDataCreate.ReturnPolicy = dataBDIn.ReturnPolicy;
					businessDataCreate.CompanyLogo = ImageName;
					_context.Add(businessDataCreate);
					await _context.SaveChangesAsync();
					return Json(new { icon = "success", title = "Información", msg = "Registro guardado!" });
				}
				//Edit
				BusinessData businessData = _context.BusinessData.FirstOrDefault();
				if (businessData.CompanyLogoPath!=null && dataBDIn.CompanyLogoFile!=null)
				{
					filePath = _pathProvider.MapPath(businessData.CompanyLogo, Folders.CompanyLogo);
					//Delete picture 
					System.IO.File.Delete(filePath); 
					//upload new picture
					ImageName = Guid.NewGuid().ToString() + dataBDIn.CompanyLogoFile.FileName; 
					filePath = await _helperUpload.UploadFilesAsync(dataBDIn.CompanyLogoFile, ImageName, Folders.CompanyLogo);
					if (filePath != null)
					{
						routeImg = directory + ImageName;
					}
				}
				if (businessData.CompanyLogoPath == null && dataBDIn.CompanyLogoFile != null)
				{
					//Upload new picture
					ImageName = Guid.NewGuid().ToString() + dataBDIn.CompanyLogoFile.FileName;
					filePath = await _helperUpload.UploadFilesAsync(dataBDIn.CompanyLogoFile, ImageName, Folders.CompanyLogo);
					if (filePath != null)
					{
						routeImg = directory + ImageName;
					}
				}
				businessData.CompanyName = dataBDIn.CompanyName;
				businessData.CompanyLogoPath = routeImg!=null?routeImg:businessData.CompanyLogoPath;
				businessData.CompanyLogo = ImageName.Length>0?ImageName:businessData.CompanyLogo;
				businessData.CompanyAddress = dataBDIn.CompanyAddress;
				businessData.Website = dataBDIn.Website;
				businessData.Email = dataBDIn.Email;
				businessData.CompanyPhone = dataBDIn.CompanyPhone;
				businessData.ReturnPolicy = dataBDIn.ReturnPolicy;
				_context.Entry(businessData).State = EntityState.Modified;
				_context.SaveChanges();
				return Json(new { icon = "success", title = "Información", msg = "Registro actualizado!" });
			}
            catch(Exception e)
            {
				_logger.LogError("Configuración",e.Message);
				return Json(new { icon = "error", title = "Informacion", msg = "Hubo un problema al guardar el registro!" });
			}          	
		}
    }
}

core-jr/Views/Config/BusinessData/BusinessData.cshtml
@model BusinessData

<div class="container">
	<div class="row row-sm">
		<div class="col-xl-6">
			<div class="card">
				<div class="card-body">
					<form id="formBusinesData" enctype="multipart/form-data">
						<div class="row">							
							<div class="row">
								<input type="hidden" name="BusinessDataId" id="BusinessDataId" value="@Model.BusinessDataId" />
								<div class="col-md-12">
									<div class="form-group">
										<label class="form-label">Nombre de la empresa <span class="text-red">*</span></label>
										<input asp-for="CompanyName" class="form-control" placeholder="Nombre de la empresa" required onchange="RemoveByClass(this,'border-red');" />
									</div>
								</div>
								<div class="">
									@{
										string ruta = Model.CompanyLogoPath == null ? "" : "/" + Model.CompanyLogoPath;
									}
									<div class="companyLogoBorder">
										<img class="img-thumbnail img-logo" id="companyLogo" src=@ruta />
									</div>
									<br />
									<div class="">
										<label class="btn-primary-light custom-file-upload">
											<input type="file" name="logoFile" id="logoFile" onchange="document.getElementById('companyLogo').src = window.URL.createObjectURL(this.files[0])" />
											Logo de la empresa <i class="mdi mdi-upload"></i>
										</label>
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group">
										<label class="form-label">Dirección</label>
										<textarea asp-for="CompanyAddress" class="form-control mb-4" placeholder="Dirección" rows="3"></textarea>
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group">
										<label class="form-label">Sitio web</label>
										<input asp-for="Website" class="form-control" placeholder="Sitio web" />
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group">
										<label class="form-label">Email</label>
										<input asp-for="Email" type="email" class="form-control" placeholder="Email" />
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group">
										<label class="form-label">Numero de telefono</label>
										<input asp-for="CompanyPhone" type="number" class="form-control" placeholder="Numero de telefono" />
									</div>
								</div>
								<div class="col-md-12">
									<div class="form-group">
										<label class="form-label">Politica de devolución</label>
										<textarea asp-for="ReturnPolicy" class="form-control mb-4" placeholder="Politica de devolución" rows="3"></textarea>
									</div>
								</div>
							</div>
							<div class="col-md-12">
								<button type="button" class="btn btn-primary-light w-lg" style="width:100%;" id="saveInfo" onclick="submitSaveBusiness()">
									<span id="spanBusinessData" name="spanBusinessData"> Guardar </span>
									<div class="spinner-border text-default" id="divBusinessData" name="divBusinessData" style="display:none;" role="status">
										<span class="sr-only"></span>
									</div>
								</button>
							</div>
						</div>						
					</form>

				</div>
			</div>
		</div>
	</div>
</div>

<script>
	
	function submitSaveBusiness() {

		AnimationButtonSent('divBusinessData', 'spanBusinessData');

		if (!ValidateByAttribute("formBusinesData", "required")) {
			
			formData = new FormData();
			formData.append("BusinessDataId", document.getElementById("BusinessDataId").value);
			formData.append("CompanyName", document.getElementById("CompanyName").value);
			formData.append("CompanyLogoFile", document.getElementById("logoFile").files[0]);
			formData.append("CompanyAddress", document.getElementById("CompanyAddress").value);
			formData.append("Website", document.getElementById("Website").value);
			formData.append("Email", document.getElementById("Email").value);
			formData.append("CompanyPhone", document.getElementById("CompanyPhone").value);
			formData.append("ReturnPolicy", document.getElementById("ReturnPolicy").value);				
			
			$.ajax({
				url: '@Url.Action("SaveBusinessData", "Config")',
				type: "POST",
				async: true,
				contentType: false,
				processData: false,
				data: formData,			
				success: function (result) {
					Swal.fire({
						icon: result.icon,
						title: result.title,
						text: result.msg,
					});
					callBusinessData();
				},
				error: function (error) {
					console.log(error);
				},
				complete: function (datos) {
				}
			});
		}
		else{
			AnimationButtonClose('divBusinessData', 'spanBusinessData');
		}		
	}

</script>